name: charm
version: 2.2
summary: charm and charm-tools
description: charmstore-client and charm-tools
confinement: strict

apps:
  charm:
    command: bin/charm
    plugs: [network, network-bind, home]

parts:
  charm:
    plugin: godeps
    go-importpath: github.com/juju/charmstore-client
    source: https://github.com/juju/charmstore-client.git
    source-tag: 2.1.2
    source-type: git
  charm-tools:
    plugin: python2
    source: https://github.com/juju/charm-tools.git
    stage-packages:
      - python-launchpadlib
      - bzr
      - git
      - mercurial
      - python-apt
      - libcurl4-openssl-dev
