name: charm
version: 2.1
summary: charm and charm-tools
description: charmstore-client and charm-tools
confinement: strict

apps:
  charm:
    command: bin/charm-cmd.wrapper
    plugs: [network, network-bind, home]

parts:
  wrapper:
    plugin: dump
    source: .
    organize:
      charm-cmd.wrapper: bin/charm-cmd.wrapper
  charm:
    plugin: godeps
    go-importpath: github.com/juju/charmstore-client
    source: https://github.com/juju/charmstore-client.git
    source-tag: 2.1.2
    source-type: git
  charm-terms:
    plugin: godeps
    go-importpath: github.com/juju/terms-client
    source: https://github.com/juju/terms-client.git
    source-tag: v1.0.0
    source-type: git
  charm-tools:
    plugin: python2
    source: https://github.com/juju/charm-tools.git
    source-branch: master
    stage-packages:
      - python-launchpadlib
      - bzr
      - mercurial
      - python-apt
  git:
    plugin: nil
    stage-packages:
      - git
    snap:
      - -lib/*/libcrypto.so*
      - -lib/*/libssl.so*
      - usr/bin/git*
      - usr/lib/git*
      - usr/lib/*/libasn1.so*
      - usr/lib/*/libcurl-gnutls.so*
      - usr/lib/*/libffi.so*
      - usr/lib/*/libgmp.so*
      - usr/lib/*/libgnutls.so*
      - usr/lib/*/libgssapi.so*
      - usr/lib/*/libgssapi_krb5.so*
      - usr/lib/*/libhcrypto.so*
      - usr/lib/*/libheimbase.so*
      - usr/lib/*/libheimntlm.so*
      - usr/lib/*/libhogweed.so*
      - usr/lib/*/libhx509.so*
      - usr/lib/*/libidn.so*
      - usr/lib/*/libk5crypto.so*
      - usr/lib/*/libkrb5.so*
      - usr/lib/*/libkrb5support.so*
      - usr/lib/*/liblber-2.4.so*
      - usr/lib/*/libldap_r-2.4.so*
      - usr/lib/*/libnettle.so*
      - usr/lib/*/libp11-kit.so*
      - usr/lib/*/libroken.so*
      - usr/lib/*/librtmp.so*
      - usr/lib/*/libsasl2.so*
      - usr/lib/*/libsqlite3.so*
      - usr/lib/*/libtasn1.so*
      - usr/lib/*/libwind.so*
      - -usr/lib/*/openssl-1.0.0*
      - -usr/share/doc/libssl1.0.0*
